/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javahotel.visao.gui;

/**
 *
 * @author Sebastiana
 */
import java.awt.Dimension;
import java.text.DateFormat;
import java.text.ParseException;
import javahotel.constante.Status;
import javahotel.constante.Constante;
import javahotel.controle.ControleHospede;
import javahotel.excecao.JavaHotelException;
import javahotel.modelo.Hospede;
import javax.crypto.SealedObject;

public class GUICadastroDeHospede extends javax.swing.JInternalFrame {
    
    private GUIHospede guiHospede;
    private Hospede hospede;

    /**
     * Creates new form GUICadastroDeHospede
     */
    public GUICadastroDeHospede() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bntLimpar = new javax.swing.JButton();
        tffonecelular = new javax.swing.JFormattedTextField();
        tfnome = new javax.swing.JTextField();
        btnGravarHospede = new javax.swing.JButton();
        jtcpf = new javax.swing.JFormattedTextField();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfemail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tffonefixo = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        tfdatanasc = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jtrg = new javax.swing.JFormattedTextField();

        setTitle("Cadastro de Hospede");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Hospede"));

        bntLimpar.setText("Limpar");

        try {
            tffonecelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnGravarHospede.setText("Gravar");
        btnGravarHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarHospedeActionPerformed(evt);
            }
        });

        try {
            jtcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnCancelar.setText("Cancelar");

        jLabel3.setText("Telefone Fixo");

        jLabel5.setText("E-mail");

        jLabel4.setText("Telefone Celular");

        jLabel2.setText("CPF");

        jLabel1.setText("Nome");

        try {
            tffonefixo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("Data de Nasc");

        try {
            tfdatanasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfdatanasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdatanascActionPerformed(evt);
            }
        });

        jLabel7.setText("RG");

        try {
            jtrg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnGravarHospede)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfemail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(tfdatanasc, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(tffonefixo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18))
                                    .addComponent(tffonecelular, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(31, 31, 31)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jtrg, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(tfnome, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(41, 41, 41)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdatanasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tffonefixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tffonecelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravarHospede)
                    .addComponent(bntLimpar)
                    .addComponent(btnCancelar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGravarHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarHospedeActionPerformed
                try {
            hospede = this.gethospede();
            ControleHospede controle = new ControleHospede();
            controle.adiciona(hospede);
            GUIMensagem.exibirMensagem("Sócio gravado com sucesso","javaclube - Sócio", false);
            this.limparCampos();
            
        }catch(JavaHotelException ex){
            GUIMensagem.exibirMensagem(ex.getMessage(), "Javaclube - Sócio", true);
            
        }

    }//GEN-LAST:event_btnGravarHospedeActionPerformed

    private void tfdatanascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdatanascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdatanascActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntLimpar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGravarHospede;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField jtcpf;
    private javax.swing.JFormattedTextField jtrg;
    private javax.swing.JFormattedTextField tfdatanasc;
    private javax.swing.JTextField tfemail;
    private javax.swing.JFormattedTextField tffonecelular;
    private javax.swing.JFormattedTextField tffonefixo;
    private javax.swing.JTextField tfnome;
    // End of variables declaration//GEN-END:variables

     public void setPosicao(){
         //Dimension d=this.getDesktopPane().getSize();
         //this.setLocation((d.width-this.getSize().width)/2,(d.height-this.getSize().height)/2);
         
    }
         // método para verificar o preenchimento do cadastro de sócio
         public Socio getSocio() throws JavaClubeException {
             int categoria = cbCategoria.getSelectedIndex();
             if (categoria == 0){
                 throw new JavaClubeException("Não foi informada a"+ "categoria do socio");
             } else {
                 socio.setCategoria(categoria - 1);
                 }
             String nome = tfnomes.getText();
             if ((nome == null) || (nome.trim().equals(""))){
                 tfnomes.requestFocus();
                 throw new JavaClubeException("Não foi informado o nome do sócio");
             }else{
                 socio.setNome(nome);
             }
             if (rbFeminino.isSelected()){
                 socio.setSexo(Sexo.Feminino.ordinal());
             } else if (rbMasculino.isSelected() ){
                 socio.setSexo(Sexo.Masculino.ordinal());
                 
             }else{
                 throw new JavaClubeException ("Não foi informado o sexo");
                 
             }
             // Data de nascimento
             DateFormat df = DateFormat.getDateInstance();
             df.setLenient (false);
             String strDataNascimento = tfDatadeNascimento.getText();
             try{
                 java.util.Date dataNascimento = df.parse(strDataNascimento);
                 socio.setDataNascimento(dataNascimento);
             }catch (ParseException ex){
                 tfDatadeNascimento.requestFocus();
                 String mensagem = "Não foi informada a data de nascimento ou"+ "\ninformada a data válida";
                 throw new JavaClubeException(mensagem);
             }catch (JavaClubeException ex){
                 tfDatadeNascimento.requestFocus();
                 throw new JavaClubeException (ex.getMessage());
             }
             socio.setTelefoneFixo(tfTelefoneFixo.getText());
             socio.setTelefoneCelular(tfTelefoneCelular.getText());
             socio.setEmail(tfEmail.getText());
             return socio;
         }
         
         public void setSocio(Socio socio){
             this.socio = socio;
             //this.exibeDadosDoSocio();
         }
         
         public void limparCampos(){
             cbCategoria.setSelectedIndex(0);
             tfnomes.setText(null);
             rbFeminino.setSelected(false);
             rbMasculino.setSelected(false);
             tfDatadeNascimento.setText(null);
             tfTelefoneFixo.setText(null);
             tfTelefoneCelular.setText(null);
             tfEmail.setText(null);
         }
         public void exibeDadosDoSocio(){
             limparCampos();
             if (socio.getCodigo()!= Constante.NOVO){
                 cbCategoria.setSelectedIndex(socio.getCategoria()+1);
                 tfNome.setText(socio.getNome());
                 if (socio.getSexo()== Sexo.Feminino.ordinal()){
                     rbFeminino.setSelected(true);
                 }
                 if (socio.getSexo() == Sexo.Masculino.ordinal()){
                     rbMasculino.setSelected(true);                     
                 }
                 DateFormat df = DateFormat.getDateInstance();
                 java.util.Date dataNascimento = socio.getDataNascimento();
                 if (dataNascimento!= null){
                     tfDatadeNascimento.setText(df.format(dataNascimento));
                 }
                 tfTelefoneFixo.setText(socio.getTelefoneFixo());
                 tfTelefoneCelular.setText(socio.getTelefoneCelular());
                 tfEmail.setText(socio.getEmail());
                 }
         }


}
